version: "3.8"
services:
  webapp:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env/development/database
      - ./.env/development/webapp

  redis:
    image: redis:7.2.4

  database:
    image: postgres:16.2
    env_file:
      - ./.env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
