services:
  webapp:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    env_file:
      - ./.env/development/webapp
      - ./.env/development/database
    tty: true

  redis:
    image: redis:7.2.4

  database:
    image: postgres:16.2
    env_file:
      - ./.env/development/database
    volumes:
      - ./db_data:/var/lib/postgresql/data

volumes:
  db_data:
  gem_cache:
